//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PopditDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bubble
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bubble()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int Id { get; set; }
        public Nullable<int> InternalId { get; set; }
        public int ProfileId { get; set; }
        public string Name { get; set; }
        public double Latitude { get; set; }
        public Nullable<double> MinLatitude { get; set; }
        public Nullable<double> MaxLatitude { get; set; }
        public double Longitude { get; set; }
        public Nullable<double> MaxLongitude { get; set; }
        public Nullable<double> MinLongitude { get; set; }
        public string AlertMsg { get; set; }
        public int RadiusId { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Url { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual Radius Radius { get; set; }
    }
}
