//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PopditDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Id { get; set; }
        public int ProfileId { get; set; }
        public int BubbleId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<System.DateTime> ServerStamp { get; set; }
    
        public virtual Bubble Bubble { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
